services:
  edge:
    image: nginx:alpine
    container_name: flash-sale-edge
    ports:
      - "1234:1234"
    volumes:
      - ./services/edge/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - load_balancer
    networks:
      - flash-sale-net

  load_balancer:
    image: nginx:alpine
    container_name: flash-sale-lb
    ports:
      - "8080:8080"
    volumes:
      - ./services/load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
    networks:
      - flash-sale-net

  api-service:
    build:
      context: ./services/api
    deploy:
      replicas: 3
    depends_on:
      - redis-cluster
      - postgres-db
      - rabbitmq
    environment:
      - PORT=5300
      - POSTGRES_DB_URL=postgresql://admin:secretpassword@postgres-db:5432/postgres
      - REDIS_HOST=redis-cluster
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - flash-sale-net

  redis-cluster:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - flash-sale-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flash-sale-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flash-sale-net

  postgres-db:
    image: postgres:15-alpine
    container_name: flash-sale-db
    environment:
      POSTGRES_DB: flash_sale_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - flash-sale-net

networks:
  flash-sale-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
  rabbitmq-data:
